name: CI

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win32
      - name: "create and enter build dir"
        shell: cmd
        run: mkdir build && cd build
      - name: "configure cmake"
        shell: cmd
        run: cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install ..
      - name: "cmake build"
        shell: cmd
        run: cd build && cmake --build .
      - name: "cmake install"
        shell: cmd
        run: cd build && cmake --install .
      - uses: actions/upload-artifact@v3
        with:
          name: ember
          path: install/
