name: CI

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - win32
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: Trass3r/setup-cpp@master
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: cmd
        run: |
          mkdir -p build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install ..
          cmake --build . --target launcher
          cmake --install .
          dir ..
